[project]
name = "example-mcp-server-project"
version = "0.1.0"
description = "This is a sample "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.2",
    "requests>=2.32.3",
    "beautifulsoup4>=4.13.4",
    "fastmcp>=2.6.1",
]
